export const MARK_ATTENDANCE_REQUEST = "MARK_ATTENDANCE_REQUEST";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_RESET = "MARK_ATTENDANCE_RESET";
export const MARK_ATTENDANCE_FAIL = "MARK_ATTENDANCE_FAIL";
