export const MARK_ATTENDANCE_REQUEST = "MARK_ATTENDANCE_REQUEST";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_FAIL = "MARK_ATTENDANCE_FAIL";

export const VIEW_ATTENDANCE_REQUEST = "VIEW_ATTENDANCE_REQUEST";
export const VIEW_ATTENDANCE_SUCCESS = "VIEW_ATTENDANCE_SUCCESS";
export const VIEW_ATTENDANCE_FAIL = "VIEW_ATTENDANCE_FAIL";

export const ADMIN_ATTENDANCE_REQUEST = "ADMIN_ATTENDANCE_REQUEST";
export const ADMIN_ATTENDANCE_SUCCESS = "ADMIN_ATTENDANCE_SUCCESS";
export const ADMIN_ATTENDANCE_FAIL = "ADMIN_ATTENDANCE_FAIL";

export const ADMIN_ALL_ATTENDANCE_REQUEST = "ADMIN_ALL_ATTENDANCE_REQUEST";
export const ADMIN_ALL_ATTENDANCE_SUCCESS = "ADMIN_ALL_ATTENDANCE_SUCCESS";
export const ADMIN_ALL_ATTENDANCE_FAIL = "ADMIN_ALL_ATTENDANCE_FAIL";
