export const GET_OLD_MESSAGES_REQUEST = "GET_OLD_MESSAGES_REQUEST";
export const GET_OLD_MESSAGES_SUCCESS = "GET_OLD_MESSAGES_SUCCESS";
export const GET_OLD_MESSAGES_FAIL = "GET_OLD_MESSAGES_FAIL";

export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_FAIL = "SEND_MESSAGES_FAIL";
export const SEND_MESSAGES_RESET = "SEND_MESSAGES_RESET";

export const RECEIVE_MESSAGES_REQUEST = "RECEIVE_MESSAGES_REQUEST";
export const RECEIVE_MESSAGES_SUCCESS = "RECEIVE_MESSAGES_SUCCESS";
export const RECEIVE_MESSAGES_FAIL = "RECEIVE_MESSAGES_FAIL";
