export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const ADMINS_REQUEST = "ADMINS_REQUEST";
export const ADMINS_SUCCESS = "ADMINS_SUCCESS";
export const ADMINS_FAIL = "ADMINS_FAIL";

export const ADMIN_CONTACTS_REQUEST = "ADMIN_CONTACTS_REQUEST";
export const ADMIN_CONTACTS_SUCCESS = "ADMIN_CONTACTS_SUCCESS";
export const ADMIN_CONTACTS_FAIL = "ADMIN_CONTACTS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
